export const projectData = [
    {
        id: 0,
        name: "Eclipse Jewelry",
        slug: "eclipse-jewelry",
        category: "frontend", // Assumed from image
        visualTone: "dark",
        accentColor: "#DFCFB9", // Beige/Gold from image
        cinematicQuote: "Elegance is the only beauty that never fades.",
        year: "2024",
        client: "Eclipse",
        role: "Frontend Developer",
        tagline: "Timeless Jewelry Collection",
        description: "A premium e-commerce experience for a luxury jewelry brand. The design focuses on minimalism and high-quality visuals to highlight the exquisiteness of the products.",
        techStack: ["React", "Tailwind CSS", "GSAP"],
        image: "/assets/projects/Websites/Eclipse-Jewelry.png",
        hoverImage: "/assets/projects/Websites/Eclipse-Jewelry.png",
        frameworks: [{ name: "React" }, { name: "Tailwind" }]
    },
    {
        id: 1,
        name: "AniStream",
        slug: "anime-library",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#FF6B6B",
        cinematicQuote: "A vibrant portal into the world of anime, designed for binge-watchers.",
        year: "2025",
        client: "Personal Project",
        role: "Frontend Dev",
        tagline: "Your Anime Sanctuary",
        description:
            "A comprehensive anime streaming library interface featuring dynamic filtering, watch lists, and immersive character art backgrounds.",
        techStack: ["React", "Framer Motion", "AniList API", "Vite"],
        image: "/assets/projects/Websites/Anime-library.png",
        hoverImage: "/assets/projects/Websites/Anime-library.png",
        frameworks: [{ name: "React" }, { name: "Framer Motion" }]
    },
    {
        id: 2,
        name: "Canvas Portfolio",
        slug: "art-portfolio",
        category: "frontend",
        visualTone: "light",
        accentColor: "#333333",
        cinematicQuote: "Minimalism that lets the artwork breathe and speak for itself.",
        year: "2024",
        client: "Studio Art",
        role: "Designer & Dev",
        tagline: "Curated Creativity",
        description:
            "A clean, gallery-style portfolio website designed for visual artists. Features masonry layouts and lightbox galleries.",
        techStack: ["Next.js", "Tailwind CSS", "Sanity CMS"],
        image: "/assets/projects/Websites/ArtPortfolio-website.png",
        hoverImage: "/assets/projects/Websites/ArtPortfolio-website.png",
        frameworks: [{ name: "Next.js" }, { name: "Tailwind" }]
    },
    {
        id: 3,
        name: "Aventador Experience",
        slug: "aventador-showcase",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#FNB800",
        cinematicQuote: "Speed, power, and aggression translated into code and pixels.",
        year: "2024",
        client: "Luxury Auto",
        role: "Creative Developer",
        tagline: "Unleash the Beast",
        description:
            "An interactive 3D product showcase for the Lamborghini Aventador. Users can customize colors and view the car from every angle.",
        techStack: ["Three.js", "React Three Fiber", "GSAP"],
        image: "/assets/projects/Websites/Aventador.png",
        hoverImage: "/assets/projects/Websites/Aventador.png",
        frameworks: [{ name: "Three.js" }, { name: "R3F" }]
    },
    {
        id: 4,
        name: "Golden Crumb",
        slug: "bakery-website",
        category: "frontend",
        visualTone: "light",
        accentColor: "#D4A373",
        cinematicQuote: "Warmth, aroma, and tradition captured in a digital storefront.",
        year: "2023",
        client: "Local Bakery",
        role: "Frontend",
        tagline: "Baked with Love",
        description:
            "A delightful website for a local artisan bakery, featuring online ordering, a gallery of treats, and a blog for recipes.",
        techStack: ["Gatsby", "GraphQL", "Stripe"],
        image: "/assets/projects/Websites/Bakery-website.png",
        hoverImage: "/assets/projects/Websites/Bakery-website.png",
        frameworks: [{ name: "Gatsby" }, { name: "Stripe" }]
    },
    {
        id: 5,
        name: "AutoShowcase",
        slug: "cars-website",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#00B4D8",
        cinematicQuote: "Connecting drivers with their dream machines through a seamless interface.",
        year: "2024",
        client: "AutoDealer",
        role: "Full Stack",
        tagline: "Drive Your Dream",
        description:
            "A comprehensive car dealership platform with advanced filtering, finance calculators, and virtual test drive booking.",
        techStack: ["Next.js", "PostgreSQL", "Prisma", "Tailwind"],
        image: "/assets/projects/Websites/Cars-website.png",
        hoverImage: "/assets/projects/Websites/Cars-website.png",
        frameworks: [{ name: "Next.js" }, { name: "PostgreSQL" }]
    },
    {
        id: 6,
        name: "Pure Organics",
        slug: "cliganic-website",
        category: "frontend",
        visualTone: "light",
        accentColor: "#7CB518",
        cinematicQuote: "Nature's best, presented with purity and transparency.",
        year: "2024",
        client: "Cliganic",
        role: "Frontend Dev",
        tagline: "Natural Beauty",
        description:
            "An e-commerce site for organic beauty products. Focused on clean typography and earthy color palettes to reflect the brand identity.",
        techStack: ["Shopify Liquid", "SCSS", "JavaScript"],
        image: "/assets/projects/Websites/Cliganic-website.png",
        hoverImage: "/assets/projects/Websites/Cliganic-website.png",
        frameworks: [{ name: "Shopify" }, { name: "SCSS" }]
    },
    {
        id: 7,
        name: "Nexus Store",
        slug: "generic-ecommerce",
        category: "frontend",
        visualTone: "light",
        accentColor: "#3F37C9",
        cinematicQuote: "A scalable, robust shopping platform built for the modern consumer.",
        year: "2023",
        client: "StartUp Inc",
        role: "Lead Dev",
        tagline: "Shop Everything",
        description:
            "A multi-vendor marketplace featuring real-time inventory updates, vendor dashboards, and secure payment processing.",
        techStack: ["MERN Stack", "Redux", "Stripe Connect"],
        image: "/assets/projects/Websites/E-commerce-webste.png",
        hoverImage: "/assets/projects/Websites/E-commerce-webste.png",
        frameworks: [{ name: "React" }, { name: "Node.js" }]
    },
    {
        id: 8,
        name: "Iron Pulse",
        slug: "gym-website",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#D00000",
        cinematicQuote: "Strength, grit, and determination. A digital space that motivates.",
        year: "2024",
        client: "Iron Gym",
        role: "UI/UX",
        tagline: "Forge Your Body",
        description:
            "A high-energy website for a fitness center. Includes class scheduling, trainer bios, and a membership portal.",
        techStack: ["Webflow", "Custom Code", "MemberStack"],
        image: "/assets/projects/Websites/Gym-website.png",
        hoverImage: "/assets/projects/Websites/Gym-website.png",
        frameworks: [{ name: "Webflow" }, { name: "JS" }]
    },
    {
        id: 9,
        name: "CineStream Legacy",
        slug: "movie-bootstrap",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#E50914",
        cinematicQuote: "The classic streaming experience, rebuilt for performance.",
        year: "2022",
        client: "Class Project",
        role: "Developer",
        tagline: "Movies Anytime",
        description:
            "A classic movie streaming interface built with Bootstrap. A robust study in responsive grid systems and component libraries.",
        techStack: ["Bootstrap 5", "jQuery", "HTML5"],
        image: "/assets/projects/Websites/Movie-bootstrap.png",
        hoverImage: "/assets/projects/Websites/Movie-bootstrap.png",
        frameworks: [{ name: "Bootstrap" }, { name: "jQuery" }]
    },
    {
        id: 10,
        name: "Movieo V1",
        slug: "movieo-v1",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#2A9D8F",
        cinematicQuote: "Our first take on the ultimate movie discovery platform.",
        year: "2023",
        client: "Personal",
        role: "Frontend",
        tagline: "Discover Cinema",
        description:
            "The first iteration of the Movieo application. Focused on fetching and displaying movie data from TMDB API.",
        techStack: ["React", "CSS Modules", "TMDB API"],
        image: "/assets/projects/Websites/Movieo-V1.png",
        hoverImage: "/assets/projects/Websites/Movieo-V1.png",
        frameworks: [{ name: "React" }, { name: "CSS" }]
    },
    {
        id: 11,
        name: "Movieo V2",
        slug: "movieo-v2",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#E76F51",
        cinematicQuote: "Refined, faster, and more personal. The sequel is always better.",
        year: "2024",
        client: "Personal",
        role: "Lead Architect",
        tagline: "Cinema Redefined",
        description:
            "The evolved version of Movieo, featuring user authentication, watchlists, and AI-powered recommendations.",
        techStack: ["Next.js 14", "Supabase", "Tailwind"],
        image: "/assets/projects/Websites/Movieo-V2.png",
        hoverImage: "/assets/projects/Websites/Movieo-V2.png",
        frameworks: [{ name: "Next.js" }, { name: "Supabase" }]
    },
    {
        id: 12,
        name: "Console Hub",
        slug: "playstation-website",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#003087",
        cinematicQuote: "For the players. A tribute to the gaming ecosystem.",
        year: "2024",
        client: "Concept",
        role: "Designer",
        tagline: "Play Has No Limits",
        description:
            "A concept landing page for a gaming console. Heavily utilizes parallax scrolling and video backgrounds to immerse the user.",
        techStack: ["React", "Framer Motion", "Styled Components"],
        image: "/assets/projects/Websites/Playstation-website.png",
        hoverImage: "/assets/projects/Websites/Playstation-website.png",
        frameworks: [{ name: "React" }, { name: "Framer" }]
    },
    {
        id: 13,
        name: "Dev Folio",
        slug: "portfolio-website",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#64FFDA",
        cinematicQuote: "My digital handshake. A first impression that lasts.",
        year: "2023",
        client: "Self",
        role: "Owner",
        tagline: "Hello World",
        description:
            "A previous iteration of my personal portfolio. simple, clean, and focused on resuming hosting and project links.",
        techStack: ["HTML", "SCSS", "JavaScript"],
        image: "/assets/projects/Websites/Portfolio-website.png",
        hoverImage: "/assets/projects/Websites/Portfolio-website.png",
        frameworks: [{ name: "HTML" }, { name: "SCSS" }]
    },
    {
        id: 14,
        name: "Spylt Energy",
        slug: "spylt-website",
        category: "frontend",
        visualTone: "experimental",
        accentColor: "#CCFF00",
        cinematicQuote: "High voltage design for a high energy drink.",
        year: "2024",
        client: "Spylt",
        role: "Frontend Dev",
        tagline: "Fuel Your Game",
        description:
            "A promotional site for a new energy drink brand. Features wild scroll animations and bold typography.",
        techStack: ["Nuxt.js", "GSAP ScrollTrigger", "WebGL"],
        image: "/assets/projects/Websites/Spylt-website.png",
        hoverImage: "/assets/projects/Websites/Spylt-website.png",
        frameworks: [{ name: "Nuxt" }, { name: "GSAP" }]
    },
    {
        id: 15,
        name: "TaskFlow",
        slug: "task-manager",
        category: "frontend",
        visualTone: "light",
        accentColor: "#4361EE",
        cinematicQuote: "Productivity is about clarity. Eliminate the noise, focus on the work.",
        year: "2024",
        client: "SaaS Startup",
        role: "Full Stack",
        tagline: "Get Things Done",
        description:
            "A collaborative task management tool for teams. Features real-time board updates, drag-and-drop kanban, and analytics.",
        techStack: ["MERN", "Socket.io", "Redux Toolkit"],
        image: "/assets/projects/Websites/Task-Manager.png",
        hoverImage: "/assets/projects/Websites/Task-Manager.png",
        frameworks: [{ name: "React" }, { name: "Socket.io" }]
    },
    {
        id: 16,
        name: "EduLearn",
        slug: "udemy-clone",
        category: "frontend",
        visualTone: "light",
        accentColor: "#A435F0",
        cinematicQuote: "Knowledge should be accessible. A platform for teachers and learners.",
        year: "2023",
        client: "EdTech Inc",
        role: "Backend Lead",
        tagline: "Learn Anything",
        description:
            "A massive open online course (MOOC) platform clone. Handles video streaming, payment processing, and course progress tracking.",
        techStack: ["Django", "Python", "React", "AWS S3"],
        image: "/assets/projects/Websites/UdemyClone-website.png",
        hoverImage: "/assets/projects/Websites/UdemyClone-website.png",
        frameworks: [{ name: "Django" }, { name: "React" }]
    },
    {
        id: 17,
        name: "Zentry",
        slug: "zentry-game",
        category: "frontend",
        visualTone: "dark",
        accentColor: "#7209B7",
        cinematicQuote: "The metaverse awaits. A gateway to the next generation of gaming.",
        year: "2025",
        client: "Zentry DAO",
        role: "Web3 Dev",
        tagline: "Enter the Nexus",
        description:
            "A Web3 gaming portal connecting players to decentralized assets. Features wallet connection and NFT visualization.",
        techStack: ["Next.js", "Ethers.js", "Wagmi", "Tailwind"],
        image: "/assets/projects/Websites/ZentryGame-website.png",
        hoverImage: "/assets/projects/Websites/ZentryGame-website.png",
        frameworks: [{ name: "Next.js" }, { name: "Web3" }]
    },
    {
        id: 18,
        name: "Drive Rentals",
        slug: "rental-cars",
        category: "frontend",
        visualTone: "light",
        accentColor: "#FB8500",
        cinematicQuote: "Your journey starts here. Frictionless booking for the open road.",
        year: "2023",
        client: "City Rentals",
        role: "Frontend",
        tagline: "Rent. Drive. Explore.",
        description:
            "A car rental booking engine. Simplified the user flow from date selection to confirmation.",
        techStack: ["React", "Date-fns", "Google Maps API"],
        image: "/assets/projects/Websites/rentalCars-website.png",
        hoverImage: "/assets/projects/Websites/rentalCars-website.png",
        frameworks: [{ name: "React" }, { name: "Maps API" }]
    }
];
