export const projectData = [
    {
        id: 1,
        name: "Mobile Accessories",
        slug: "mobile-accessories",
        category: "uiux",
        visualTone: "dark",
        accentColor: "#E0CCBB",
        cinematicQuote: "Merging the tactile feeling of a showroom with digital convenience.",
        year: "2024",
        client: "TechGear Inc.",
        role: "Lead Frontend",
        tagline: "A Digital Flagship Store",
        description:
            "A premium online store specializing in high-end phone accessories. The goal was to create a shopping experience that feels as premium as the products themselves.",
        techStack: ["Next.js", "React", "GSAP", "Shopify"],
        image: "/assets/projects/mobile-accessories-store.jpg",
        hoverImage: "/assets/projects/mobile-accessories-store.jpg",
        frameworks: [{ name: "React" }, { name: "GSAP" }]
    },
    {
        id: 2,
        name: "Plant Shop",
        slug: "plant-shop",
        category: "frontend",
        visualTone: "light",
        accentColor: "#4A7A58",
        cinematicQuote: "The web is often rigid. We wanted this site to feel organic, growing, and alive.",
        year: "2023",
        client: "GreenLife",
        role: "Full Stack",
        tagline: "Digital Botany",
        description:
            "An online sanctuary for plant lovers. This e-commerce platform specializes in rare and decorative plants.",
        techStack: ["Astro", "React", "Contentful", "Tailwind"],
        image: "/assets/projects/plant-shop.jpg",
        hoverImage: "/assets/projects/plant-shop.jpg",
        frameworks: [{ name: "Astro" }, { name: "Tailwind" }]
    },
    {
        id: 3,
        name: "Apple Tech",
        slug: "apple-tech",
        category: "fullstack",
        visualTone: "light",
        accentColor: "#0071E3",
        cinematicQuote: "Transparency was the north star. Every pixel communicates clarity and trust.",
        year: "2024",
        client: "iResell",
        role: "Architect",
        tagline: "Trust by Design",
        description:
            "A specialized marketplace for refurbished Apple products. The site aims to restore trust in the second-hand market.",
        techStack: ["Blazor", "C#", "Azure", "CosmosDB"],
        image: "/assets/projects/apple-tech-store.jpg",
        hoverImage: "/assets/projects/apple-tech-store.jpg",
        frameworks: [{ name: "Blazor" }, { name: "C#" }]
    },
    {
        id: 4,
        name: "Gadget Store",
        slug: "gadget-store",
        category: "fullstack",
        visualTone: "dark",
        accentColor: "#FF0000",
        cinematicQuote: "If the user can't find it, it doesn't exist. Information architecture was the design.",
        year: "2023",
        client: "CircuitCity",
        role: "UI Engineer",
        tagline: "Order from Chaos",
        description:
            "A high-volume electronics retailer. The site features tens of thousands of products.",
        techStack: ["Vue.js", "Laravel", "Algolia"],
        image: "/assets/projects/electronics-store.jpg",
        frameworks: [{ name: "Vue" }, { name: "Algolia" }]
    },
    {
        id: 5,
        name: "Home Decor",
        slug: "home-decor",
        category: "uiux",
        visualTone: "light",
        accentColor: "#8B5A2B",
        cinematicQuote: "We wanted users to 'feel' the wood grain and 'touch' the velvet through the screen.",
        year: "2023",
        client: "Artisan Living",
        role: "Creative Dev",
        tagline: "Tactile Digital",
        description:
            "A boutique marketplace for artisan furniture and decor. The focus is on storytelling.",
        techStack: ["Angular", "Three.js", "Firebase", "RxJS"],
        image: "/assets/projects/home-decor-store.jpg",
        frameworks: [{ name: "Angular" }, { name: "Three.js" }]
    },
    {
        id: 6,
        name: "Game Store",
        slug: "game-store",
        category: "frontend",
        visualTone: "experimental",
        accentColor: "#9D00FF",
        cinematicQuote: "The UI itself is a game. Hover effects, sounds, and unlocks make browsing feel like playing.",
        year: "2024",
        client: "Pixel Play",
        role: "Lead Engineer",
        tagline: "Player One Ready",
        description:
            "A digital storefront for gamers. Dark mode default, neon accents, and a focus on community.",
        techStack: ["SvelteKit", "Cloudflare", "tRPC", "WebGL"],
        image: "/assets/projects/game-store.jpg",
        frameworks: [{ name: "SvelteKit" }, { name: "WebGL" }]
    },
];
